// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDNq-7MIn0y_lYbk7K17b4AjvQnLkfwJ4',
    appId: '1:438464212932:web:d3c457d45eddee6a957e91',
    messagingSenderId: '438464212932',
    projectId: 'lab3-1-4cc94',
    authDomain: 'lab3-1-4cc94.firebaseapp.com',
    storageBucket: 'lab3-1-4cc94.appspot.com', iosBundleId: '',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDNq-7MIn0y_lYbk7K17b4AjvQnLkfwJ4',
    appId: '1:438464212932:android:63649bcab2f0c4da957e91',
    messagingSenderId: '438464212932',
    projectId: 'lab3-1-4cc94',
    storageBucket: 'lab3-1-4cc94.appspot.com', iosBundleId: '', authDomain: '',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDNq-7MIn0y_lYbk7K17b4AjvQnLkfwJ4',
    appId: '1:438464212932:ios:7c404fddf32ce4bf957e91',
    messagingSenderId: '438464212932',
    projectId: 'lab3-1-4cc94',
    storageBucket: 'lab3-1-4cc94.appspot.com',
    iosBundleId: 'lab3-1', authDomain: '',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDNq-7MIn0y_lYbk7K17b4AjvQnLkfwJ4',
    appId: '1:438464212932:ios:7c404fddf32ce4bf957e91',
    messagingSenderId: '438464212932',
    projectId: 'lab3-1-4cc94',
    storageBucket: 'lab3-1-4cc94.appspot.com',
    iosBundleId: 'lab3-1', authDomain: '',
  );
}

class FirebaseOptions {
  const FirebaseOptions({required String apiKey, required String appId, required String messagingSenderId, required String projectId, required String storageBucket, required String iosBundleId, required String authDomain});
}